### ISSUE TITLE
Perhaps add some GICT Docs?

### ISSUE THREAD

**Issue by PIRUX-LLC** [Gordae/Glint#1]
Not a big issue, but GICT could use some help files... :)

**Comment by Winksplorer** [comment]
Ohh, back in the days when I never documented any of my projects...
I'll put some GICT docs in the wiki, although I cannot guarantee that they will be accurate. As I wrote GICT around a year ago, with no comments.

PS: I'm currently working on 4.0 of this project, which has a better language and will have docs.

**Comment by Winksplorer** [comment]
To be honest, GICT is a pretty bad language, I wrote it when I was still new to C#.

I'm working on a better language for a new version of Glint.
should be released in around November or around that.

**Comment by Winksplorer** [comment]
I don't have anymore plans for this project. Cosmos is too slow and unstable to do anything.
